### ISSUE TITLE
bitbake causes ImportError: cannot import name data

### ISSUE THREAD

**Issue by hlieberman-gov** [EttusResearch/e300-manifest#1]
Helllo!

It looks like the version of bitbake specified in this config causes a conflict between beautifulsoup and html5lib.

```
Traceback (most recent call last):
  File "/home/hlieberman/Code/oe-repo/bitbake/bin/bitbake", line 31, in <module>
    import bb
  File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/__init__.py", line 77, in <module>
    from bb import fetch2 as fetch
  File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/fetch2/__init__.py", line 1769, in <module>
    from . import wget
  File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/fetch2/wget.py", line 40, in <module>
    from   bs4 import BeautifulSoup
  File "/home/hlieberman/Code/oe-repo/bitbake/lib/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/home/hlieberman/Code/oe-repo/bitbake/lib/bs4/builder/__init__.py", line 311, in <module>
    from . import _html5lib
  File "/home/hlieberman/Code/oe-repo/bitbake/lib/bs4/builder/_html5lib.py", line 57, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
/home/hlieberman/Code/oe-repo/bitbake/lib/bb/event.py:118: RuntimeWarning: Parent module 'bb' not found while handling absolute import
  from bb.msg import BBLogFormatter
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/event.py", line 118, in print_ui_queue
    from bb.msg import BBLogFormatter
  File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/__init__.py", line 77, in <module>
    from bb import fetch2 as fetch
  File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/fetch2/__init__.py", line 39, in <module>
    from bb import data
ImportError: cannot import name data
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/event.py", line 118, in print_ui_queue
    from bb.msg import BBLogFormatter
  File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/__init__.py", line 77, in <module>
    from bb import fetch2 as fetch
  File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/fetch2/__init__.py", line 39, in <module>
    from bb import data
ImportError: cannot import name data
exit 1
```

I believe this is an instance of https://bugs.launchpad.net/beautifulsoup/+bug/1603299.

**Comment by sdunnagan** [comment]
I have the same question.

**Comment by black-pigeon** [comment]
> Helllo!
> 
> It looks like the version of bitbake specified in this config causes a conflict between beautifulsoup and html5lib.
> 
> ```
> Traceback (most recent call last):
>   File "/home/hlieberman/Code/oe-repo/bitbake/bin/bitbake", line 31, in <module>
>     import bb
>   File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/__init__.py", line 77, in <module>
>     from bb import fetch2 as fetch
>   File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/fetch2/__init__.py", line 1769, in <module>
>     from . import wget
>   File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/fetch2/wget.py", line 40, in <module>
>     from   bs4 import BeautifulSoup
>   File "/home/hlieberman/Code/oe-repo/bitbake/lib/bs4/__init__.py", line 30, in <module>
>     from .builder import builder_registry, ParserRejectedMarkup
>   File "/home/hlieberman/Code/oe-repo/bitbake/lib/bs4/builder/__init__.py", line 311, in <module>
>     from . import _html5lib
>   File "/home/hlieberman/Code/oe-repo/bitbake/lib/bs4/builder/_html5lib.py", line 57, in <module>
>     class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
> AttributeError: 'module' object has no attribute '_base'
> /home/hlieberman/Code/oe-repo/bitbake/lib/bb/event.py:118: RuntimeWarning: Parent module 'bb' not found while handling absolute import
>   from bb.msg import BBLogFormatter
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
>     func(*targs, **kargs)
>   File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/event.py", line 118, in print_ui_queue
>     from bb.msg import BBLogFormatter
>   File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/__init__.py", line 77, in <module>
>     from bb import fetch2 as fetch
>   File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/fetch2/__init__.py", line 39, in <module>
>     from bb import data
> ImportError: cannot import name data
> Error in sys.exitfunc:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
>     func(*targs, **kargs)
>   File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/event.py", line 118, in print_ui_queue
>     from bb.msg import BBLogFormatter
>   File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/__init__.py", line 77, in <module>
>     from bb import fetch2 as fetch
>   File "/home/hlieberman/Code/oe-repo/bitbake/lib/bb/fetch2/__init__.py", line 39, in <module>
>     from bb import data
> ImportError: cannot import name data
> exit 1
> ```
> 
> I believe this is an instance of https://bugs.launchpad.net/beautifulsoup/+bug/1603299.

Hi,
Have you sloved this problem? I have the same problem.
